### ISSUE TITLE
Add filters for URL response time chart

### ISSUE THREAD

**Issue by Pravin-Parkhi** [DefragLabs/uptime#12]
As per current implementation, frontend shows all the results in order to visualize response time for any particular URL in chart. Because of it, the chart became cluttered and difficult to read. This problem can be efficiently solved by implementing filters for a chart, such as showing data for last 1hr, 6hr, etc.

It would be really good if we implement below filters with below values.
**1. Monitoring URLs listing page**
_Filter Name - Sort_
 Values - Sort by status UP
             - Sort by status Down
             - Sort by name

**2. Monitoring URL details Page**
_FIlter Name - Result for_
Values - Last 1hrs
            - Last 3hrs
            - Last 6hrs
            - Last 1 day
            - Last 1 week
            - Last 1 month

**Comment by Dineshs91** [comment]
@Pravin-Parkhi We will have `1 week` and `1 month` also for monitoring url details page.

**Comment by Dineshs91** [comment]
For the filters in monitoring urls listing page will it be done in the `frontend` ? @Pravin-Parkhi

**Comment by Pravin-Parkhi** [comment]
> @Pravin-Parkhi We will have `1 week` and `1 month` also for monitoring url details page.

Sure, I will update an issue accordingly.

**Comment by Dineshs91** [comment]
Added support for this. In the same url pass `interval` query param.

It has the following format

`?interval={value}-{unit}`

**Example:**

`?interval=1-hour`
`?interval=1-day`
