### ISSUE TITLE
Need changes in "GET /integrations" API response 

### ISSUE THREAD

**Issue by Pravin-Parkhi** [DefragLabs/uptime#17]
As of now, API is returning an array of objects in which each object is an integration. Each object contains keys for all integration types such as email, slack, etc..

I am thinking of creating tabs view for each integration type where we show a view for adding integration on one side and its respective list on another side. This view would contribute in making user experience better and with the current API response, it is not possible to achive such view.

In order to support tabs view UI, could you please modify the response and send it in below format?
```
data: {
  email: [{'id': 1, email: 'test@test.com', type:'email'}],
  slack: [{"type": "slack", "webhookURL": "http://localhost/"}],
  pager_duty: [{"type": "pagerduty","pdAction": "trigger","pdSeverity": "critical","pdRoutingKey": "test"}]
}
```

**Comment by Dineshs91** [comment]
Fixed.
